#### Quick Transformer lol

In [205]:
import torch
import torch.nn as nn

neurons = nn.Linear(1,2)

embedding = nn.Embedding(10, 3)

print(neurons.weight)



Parameter containing:
tensor([[-0.0309],
        [ 0.9235]], requires_grad=True)


In [321]:
# an Embedding matrix of 10 embeddings with 3 dimensions each
embedding = nn.Embedding(10, 3)

# a batch of 2 samples of 1 index each
input = torch.LongTensor([[9],[0]])

print('THE INPUTS \n',input)

# what does the embedding matrix look like?
print('THE EMBEDDING MATRIX \n',embedding.weight)

# what is the result of the input embedding?
print('EMBEDDINGS FOR THE GIVEN INPUTS \n',embedding(input))

THE INPUTS 
 tensor([[9],
        [0]])
THE EMBEDDING MATRIX 
 Parameter containing:
tensor([[ 1.5677, -1.0696,  0.1981],
        [ 0.7965, -1.1903, -0.3554],
        [-0.1392,  2.3178,  1.5381],
        [-0.1673,  0.5224,  0.8070],
        [ 0.3306,  0.0067, -0.5437],
        [ 0.3219,  0.9471, -1.1960],
        [ 1.1326,  1.8201,  0.6771],
        [-0.6820, -0.7878, -0.5440],
        [-0.7984,  0.3540,  1.7827],
        [-2.1361, -0.0390,  0.4890]], requires_grad=True)
EMBEDDINGS FOR THE GIVEN INPUTS 
 tensor([[[-2.1361, -0.0390,  0.4890]],

        [[ 1.5677, -1.0696,  0.1981]]], grad_fn=<EmbeddingBackward0>)


notes on nn.Embedding in the Bigram Language Model

the embedding module creates a lookup table with a configurable number of rows and columns. 
- number of rows is the number of unique words in the vocabulary,
- columns is the size of the word embeddings.

 The embedding module is initialized with random values, and the embeddings are learned during training.

 

#### Import the dataset

In [334]:
with open('input.txt','r', encoding='utf-8') as f:
    text = f.read()


In [341]:
print('the length of the text is ',len(text))
print(text[:200])

the length of the text is  1115394
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you


## OK

embedding layer is a lookup table, 

- input to the embedding layer is a list of indices
- output is a list of word (token) embeddings.

lets turn our dataset into a list of indices, and feed it to the embedding layer. 

#### how do we do this?
(We're doing a character level model)

[x] we find all possible vocab words (letters) in datataset 
    - separate the dataset by letters, make a set of them, a list 
- tokenize the dataset wrt the vocab 
    - enumerate every element in the list 
    - make a function that returns index num for each string
        - and a string for each num
- pass all of these token indices into the embedding table
    - turn entire dataset into nums wrt this tokenization strat
- get back all the embeddings  

In [361]:
# FIND ALL POSSIBLE VOCAB WORDS IN DATASET 

from pprint import pprint

vocab_letters  = sorted(list(set(text)))
print(''.join(vocab_letters))
print(len(vocab_letters))

# this is the entirety of our vocab for our word level transformer 


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [ ]:
# INDEX ALL OF THE WORDS




In [ ]:
# MAKE A FUNCTION THAT ENCODES STR -> IDX AND
# DECODES  IDX -> BACK TO STR